
default: &default
  host: 10.1.1.11 # utilizar na velow
  adapter: postgresql
  encoding: unicode
  user: postgres   # utilizar na velow
  timeout: 5000   # utilizar na velow
  password: p0stgr3s # utilizar na velow
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: vulnerabilities_development

test:
  <<: *default
  database: vulnerabilities_test

production:
  <<: *default
  database: vulnerabilities_production
  username: vulnerabilities
  password: <%= ENV['VULNERABILITIES_DATABASE_PASSWORD'] %>
